
namespace DeepSigma.SupplyChainManagement.BusinessInnovation;

/// <summary>
/// Value creation utilities provide methods for calculating the net utility and profits generated by a flow of goods or services. These calculations help businesses assess the overall value created by their operations, taking into account both the benefits (gross utility) and the costs incurred to achieve those benefits. By understanding the net utility and profits, businesses can make informed decisions about pricing, production, and resource allocation to maximize customer satisfaction and business success.
/// </summary>
public static class ValueCreationUtilities
{
    /// <summary>
    /// Compute the net utility of a flow of goods or services by subtracting the cost from the gross utility. This calculation helps to determine the overall value created by the flow, taking into account both the benefits (gross utility) and the costs incurred to achieve those benefits. A positive net utility indicates that the flow is creating value, while a negative net utility suggests that the costs outweigh the benefits, indicating a potential area for improvement or reevaluation of the flow's efficiency and effectiveness.
    /// Utility is a measure of the satisfaction or value that a customer derives from consuming a product or service, while cost represents the expenses incurred to produce or provide that product or service. By calculating net utility, businesses can assess the profitability and value proposition of their offerings, guiding strategic decisions and resource allocation to maximize customer satisfaction and business success.
    /// </summary>
    /// <param name="gross_utility"></param>
    /// <param name="cost"></param>
    /// <returns></returns>
    public static decimal ComputeNetUtility(decimal gross_utility, decimal cost) => gross_utility - cost;

    /// <summary>
    /// Computes the profit generated by a flow of goods or services based on the flow rate, price per unit, and cost per unit. The profit is calculated as the difference between the revenue generated from selling the goods or services (flow rate multiplied by price per unit) and the total cost incurred to produce or provide those goods or services (flow rate multiplied by cost per unit). This utility can be used to evaluate the profitability of a process or operation and make informed decisions about pricing, production, and resource allocation.
    /// </summary>
    /// <param name="flow_rate"></param>
    /// <param name="price_per_unit"></param>
    /// <param name="cost_per_unit"></param>
    /// <returns></returns>
    public static decimal ComputeProfits(decimal flow_rate, decimal price_per_unit, decimal cost_per_unit) => flow_rate * (price_per_unit - cost_per_unit);

    /// <summary>
    /// Calculates the economic value created by a business based on invested capital, return on invested capital, and
    /// the weighted average cost of capital.
    /// </summary>
    /// <remarks>This method provides a measure of whether a company is creating or destroying value relative
    /// to its cost of capital. A positive result indicates value creation, while a negative result indicates value
    /// destruction.</remarks>
    /// <param name="invested_capital">The total amount of capital invested in the business. Must be a non-negative value.</param>
    /// <param name="return_on_invested_capital">The rate of return generated on the invested capital, expressed as a decimal (for example, 0.08 for 8%).</param>
    /// <param name="weighted_average_cost_of_capital">The average rate of return required by investors, expressed as a decimal (for example, 0.05 for 5%).</param>
    /// <returns>A decimal value representing the economic value created, calculated as the product of invested capital and the
    /// difference between return on invested capital and weighted average cost of capital.</returns>
    public static decimal EconomicValueCreated(decimal invested_capital, decimal return_on_invested_capital, decimal weighted_average_cost_of_capital) => invested_capital * (return_on_invested_capital - weighted_average_cost_of_capital);

    /// <summary>
    /// Productivity is a measure of the efficiency of a production process, calculated as the ratio of revenue generated to the cost incurred. It indicates how effectively resources are being utilized to produce goods or services. A higher productivity value suggests that more revenue is being generated per unit of cost, which can be an indicator of a more efficient and profitable operation. Conversely, a lower productivity value may indicate inefficiencies in the production process, suggesting that costs are high relative to the revenue generated, and there may be opportunities for improvement in resource utilization or cost management.
    /// </summary>
    /// <param name="revenue"></param>
    /// <param name="cost"></param>
    /// <returns></returns>
    public static decimal ComputeProductivity(decimal revenue, decimal cost) => cost == 0 ? decimal.MaxValue : revenue / cost;

    /// <summary>
    /// Labor productivity is a measure of the efficiency of labor in producing goods or services, calculated as the ratio of revenue generated to the labor cost incurred. It indicates how effectively labor resources are being utilized to generate revenue. A higher labor productivity value suggests that more revenue is being generated per unit of labor cost, which can be an indicator of a more efficient and profitable operation. Conversely, a lower labor productivity value may indicate inefficiencies in labor utilization, suggesting that labor costs are high relative to the revenue generated, and there may be opportunities for improvement in workforce management or labor cost control.
    /// </summary>
    /// <param name="revenue"></param>
    /// <param name="labor_cost"></param>
    /// <returns></returns>
    public static decimal ComputeLaborProductivity(decimal revenue, decimal labor_cost) => labor_cost == 0 ? decimal.MaxValue : revenue / labor_cost;

    /// <summary>
    /// Return on Invested Capital (ROIC) is a financial performance metric that measures the return generated by a company on the capital invested in its operations. 
    /// It is calculated by dividing the net operating profit after tax (NOPAT) by the invested capital. ROIC provides insight into how effectively a company is using its capital to generate profits and can be used to compare the performance of different companies or evaluate the efficiency of a company's operations over time. A higher ROIC indicates that a company is generating more profit per unit of invested capital, which can be a sign of strong financial performance and value creation for shareholders.
    /// </summary>
    /// <param name="net_operating_profit_after_tax"></param>
    /// <param name="invested_capital"></param>
    /// <returns></returns>
    public static decimal ReturnOnInvestedCapital(decimal net_operating_profit_after_tax, decimal invested_capital) 
        => invested_capital == 0 
        ? decimal.MaxValue 
        : net_operating_profit_after_tax / invested_capital; // Avoid division by zero, implies infinite return on invested capital

    /// <summary>
    /// Net operating profit is a measure of the profitability of a company's core business operations, calculated as the difference between total revenue and total costs (both fixed and variable) associated with producing goods or services. 
    /// It provides insight into the company's ability to generate profit from its primary activities, excluding any non-operating income or expenses. A positive net operating profit indicates that the company is generating more revenue than it is incurring in costs, while a negative net operating profit suggests that the company may be struggling to cover its operational expenses, which could be a sign of inefficiency or financial challenges that may require attention and improvement.
    /// </summary>
    /// <param name="Revenue"></param>
    /// <param name="FixedCost"></param>
    /// <param name="VariableCostPerUnit"></param>
    /// <param name="flow_rate"></param>
    /// <returns></returns>
    public static decimal NetOperatingProfit(decimal Revenue, decimal FixedCost, decimal VariableCostPerUnit, decimal flow_rate)
    {
        decimal TotalCost = FixedCost + (VariableCostPerUnit * flow_rate);
        return Revenue - TotalCost;
    }

    /// <summary>
    /// Return on Invested Capital (ROIC) can also be calculated using the flow rate, price, invested capital, fixed cost, and variable cost per unit. 
    /// This method computes the revenue generated from the flow of goods or services (flow rate multiplied by price), subtracts the total cost (fixed cost plus variable cost per unit multiplied by flow rate) to get the net operating profit after tax, and then divides that by the invested capital to determine the ROIC. 
    /// This approach allows businesses to evaluate their return on invested capital based on operational metrics and financial inputs, providing insights into the efficiency and profitability of their investments in relation to their operational performance.
    /// </summary>
    /// <param name="flow_rate"></param>
    /// <param name="price"></param>
    /// <param name="invested_capital"></param>
    /// <param name="fixed_cost"></param>
    /// <param name="variable_cost_per_unit"></param>
    /// <returns></returns>
    public static decimal ReturnOnInvestedCapital(decimal flow_rate, decimal price, decimal invested_capital, decimal fixed_cost, decimal variable_cost_per_unit)
    {
        decimal revenue = flow_rate * price;
        decimal net_operating_profit = NetOperatingProfit(revenue, fixed_cost, variable_cost_per_unit, flow_rate);
        
        decimal company_margin = ComputeCompanyMargin(net_operating_profit, revenue);
        decimal capital_turns = ComputeAssetTurns(flow_rate, invested_capital, price);
        return company_margin * capital_turns;
    }

    /// <summary>
    /// Calculates the profit margin for a company based on its net operating profit and total revenue.
    /// </summary>
    /// <remarks>If revenue is zero, the method returns <see cref="decimal.MaxValue"/> to avoid division by
    /// zero. This behavior indicates that the margin is undefined in such cases.</remarks>
    /// <param name="net_operating_profit">The net operating profit of the company. This value is used as the numerator in the margin calculation.</param>
    /// <param name="revenue">The total revenue of the company. If this value is zero, the method returns <see cref="decimal.MaxValue"/> to
    /// indicate an undefined margin.</param>
    /// <returns>The profit margin as a decimal value, calculated as net operating profit divided by revenue. Returns <see
    /// cref="decimal.MaxValue"/> if revenue is zero.</returns>
    public static decimal ComputeCompanyMargin(decimal net_operating_profit, decimal revenue)
    {
        return revenue == 0 ? decimal.MaxValue : net_operating_profit / revenue;    
    }


    /// <summary>
    /// Calculates the asset turnover ratio, which measures how efficiently invested capital is used to generate
    /// revenue.
    /// </summary>
    /// <remarks>Use this method to assess the effectiveness of asset utilization in generating sales. A
    /// higher ratio indicates more efficient use of assets.</remarks>
    /// <param name="flow_rate">The total revenue generated over a specific period. Must be a non-negative value.</param>
    /// <param name="invested_capital_amount">The total amount of capital invested in assets. Must be greater than zero to avoid division by zero.</param>
    /// <param name="price">The price per unit of the asset, used to determine total revenue.</param>
    /// <returns>The asset turnover ratio as a decimal value. Returns decimal.MaxValue if invested_capital_amount is zero.</returns>
    public static decimal ComputeAssetTurns(decimal flow_rate, decimal invested_capital_amount, decimal price)
    {
        return invested_capital_amount == 0 
            ? decimal.MaxValue 
            : (flow_rate * price) / invested_capital_amount;
    }

    /// <summary>
    /// Computes the percentage change in profit resulting from a percentage change in revenue, given the gross margin as a percentage of revenue and the net profit percentage. This calculation helps to understand how changes in revenue can impact profitability, taking into account the cost structure of the business as reflected in the gross margin and net profit percentages. A higher gross margin and net profit percentage can amplify the effect of revenue changes on profit, while lower margins may dampen this effect. This utility can be useful for financial analysis and decision-making related to pricing, sales strategies, and cost management.
    /// </summary>
    /// <param name="revenue_percentage_increase">The percentage increase in revenue. Must be a non-negative value.</param>
    /// <param name="gross_margin_as_percent_of_revenue">The gross margin as a percentage of revenue. Must be a non-negative value.</param>
    /// <param name="net_profit_percentage">The net profit percentage. Must be greater than zero to avoid division by zero.</param>
    /// <returns>The percentage change in profit resulting from the revenue change. Returns <see cref="decimal.MaxValue"/> if net_profit_percentage is zero.</returns>
    public static decimal ComputePercentageChangeInProfitFromRevenueChange(decimal revenue_percentage_increase, decimal gross_margin_as_percent_of_revenue, decimal net_profit_percentage)
    {
        return net_profit_percentage == 0 ? decimal.MaxValue 
            : (revenue_percentage_increase * gross_margin_as_percent_of_revenue) / net_profit_percentage;
    }
}
